framework:
    secret: '%env(APP_SECRET)%'
    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax
        storage_factory_id: session.storage.factory.native

    php_errors:
        log: true

    serializer:
        mapping:
            path:
                # Indicamos que nuestros grupos de serializacion van a estar en esta carpeta
                - '%kernel.project_dir%/config/api_platform/serialization'

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
